from __future__ import annotations

# Static configuration data for the intelligence layer.
# Kept separate from intelligence.py so the logic file stays readable.

# ── Trusted news sources ──────────────────────────────────────────────────────

TRUSTED_SOURCES = {
    s.lower()
    for s in [
        # Global
        "FIFA.com",
        "ESPN FC",
        "ESPN",
        "BBC Sport",
        "BBC Sport Football",
        "The Athletic",
        "Goal.com",
        "Transfermarkt",
        "Reuters",
        "Reuters Sports",
        "Associated Press",
        "Associated Press Sports",
        "Sky Sports",
        "Sky Sports Football",
        "OptaJoe",
        "WhoScored",
        "FourFourTwo",
        "AP",
        # UEFA
        "UEFA.com",
        "Marca",
        "AS.com",
        "L'Equipe",
        "Gazzetta dello Sport",
        "Kicker",
        "Football Italia",
        "The Guardian",
        "The Guardian Football",
        "Fabrizio Romano",
        "Voetbal International",
        "A Bola",
        "Record",
        "Record (Portugal)",
        # CONMEBOL
        "TyC Sports",
        "Ole.com.ar",
        "Globo Esporte",
        "Lance!",
        "El Comercio",
        "ESPN Deportes",
        "CONMEBOL.com",
        "ESPN",
        # CONCACAF
        "Concacaf.com",
        "The Equalizer Soccer",
        "Ives Soccer",
        "SBI Soccer",
        "Medio Tiempo",
        "Record (Mexico)",
        "CanadaSoccerNews",
        "Sportsnet",
        "TSN",
        "The Canadian Press",
        # CAF
        "BBC Africa Sport",
        "CAF Online",
        "CAFOnline.com",
        "cafonline.com",
        "KickOff",
        "Goal.com Africa",
        "SuperSport Africa",
        "SuperSport",
        "Futaa.com",
        "The Nation Sports",
        "Pan Africa Football",
        "Algérie Presse Service",
        # AFC
        "the-afc.com",
        "AFC.com",
        "Fox Sports Asia",
        "Goal.com Asia",
        "Yonhap Sports",
        "Nikkan Sports",
        "Gulf News Sport",
        "Saudi Gazette Sport",
        "Arab News",
        "Saudi Pro League",
        "Saudi Pro League Official Website",
        "UzDaily.uz",
        "Jordan Times",
        # OFC
        "oceaniafootball.com",
        "Stuff Sport",
        "Fox Sports Australia",
        "The Roar",
        # Other credible outlets that appeared in results
        "Al Jazeera",
        "Le Monde",
        "Swiss Football Association",
        "Inside World Football",
        "CNN Brasil",
        "The Washington Post",
        "El País",
        "Bundesliga",
        "HRT",
        "Croatia Week",
        "NFSBiH.ba",
        "Footy Headlines",
        "blue News",
        "Blick",
        "Egypt Today",
        "The Brussels Times",
        "beIN SPORTS",
        "7NEWS Australia",
        "News Ghana",
        "Jordan Pulse",
        "La Presse de Tunisie",
    ]
}

# ── Team name aliases ─────────────────────────────────────────────────────────
# Used to detect cross-team news articles that mention a different team.

TEAM_ALIASES: dict[str, set[str]] = {
    # Group A
    "mex": {
        "mexico",
        "el tri",
        "el tricolor",
        "tricolor",
        "los aztecas",
        "mexican",
        "selección mexicana",
        "seleccion mexicana",
        "selección de méxico",
        "seleccion de mexico",
    },
    "rsa": {"south africa", "bafana bafana", "bafana"},
    "kor": {"korea republic", "south korea", "korea", "taeguk warriors", "asian tigers"},
    "cze": {"czechia", "czech republic", "czech"},
    # Group B
    "can": {"canada", "canadian", "les rouges", "the reds"},
    "bih": {
        "bosnia",
        "bosnia-herzegovina",
        "bosnia and herzegovina",
        "bosnia & herzegovina",
        "zmajevi",
        "the dragons",
        "golden lilies",
    },
    "qat": {"qatar", "qatari", "the maroons", "maroons"},
    "sui": {"switzerland", "swiss", "la nati", "nati"},
    # Group C
    "bra": {
        "brazil",
        "brasil",
        "a canarinha",
        "canarinha",
        "seleção",
        "selecao",
        "a verde-amarela",
        "verde-amarela",
        "seleção brasileira",
        "selecao brasileira",
        "brazilian",
    },
    "mar": {"morocco", "moroccan", "atlas lions", "équipe du maroc", "equipe du maroc"},
    "hai": {"haiti", "haitian", "les grenadiers", "les bicolores", "grenadiers"},
    "sco": {"scotland", "scottish"},
    # Group D
    "usa": {
        "usa",
        "usmnt",
        "united states",
        "u.s.",
        "u.s.a.",
        "stars and stripes",
        "american",
        "us men",
        "us soccer",
    },
    "par": {
        "paraguay",
        "paraguayan",
        "la albirroja",
        "albirroja",
        "selección paraguaya",
        "seleccion paraguaya",
        "selección de paraguay",
        "seleccion de paraguay",
    },
    "aus": {"australia", "socceroos", "australian"},
    "tur": {"türkiye", "turkiye", "turkey", "turkish", "milli takım", "milli takim"},
    # Group E
    "ger": {
        "germany",
        "german",
        "die mannschaft",
        "mannschaft",
        "die nationalmannschaft",
        "nationalmannschaft",
        "dfb",
    },
    "cur": {"curaçao", "curacao"},
    "civ": {
        "côte d'ivoire",
        "cote d'ivoire",
        "ivory coast",
        "ivorian",
        "les éléphants",
        "les elephants",
        "elephants",
    },
    "ecu": {
        "ecuador",
        "ecuadorian",
        "la tri",
        "la tricolor",
        "selección ecuatoriana",
        "seleccion ecuatoriana",
        "selección de ecuador",
        "seleccion de ecuador",
    },
    # Group F
    "ned": {"netherlands", "dutch", "holland", "oranje", "het nederlands elftal"},
    "jpn": {"japan", "japanese", "samurai blue"},
    "swe": {"sweden", "swedish", "blågult", "blagult"},
    "tun": {"tunisia", "tunisian", "eagles of carthage", "équipe de tunisie", "equipe de tunisie"},
    # Group G
    "bel": {"belgium", "belgian", "red devils", "les diables rouges", "rode duivels"},
    "egy": {"egypt", "egyptian", "the pharaohs", "pharaohs"},
    "irn": {"iran", "ir iran", "iranian", "team melli"},
    "nzl": {"new zealand", "all whites", "kiwis"},
    # Group H
    "esp": {
        "spain",
        "spanish",
        "la roja",
        "la furia española",
        "la furia espanola",
        "la furia",
        "selección española",
        "seleccion española",
        "seleccion espanola",
        "la seleccion española",
        "la seleccion espanola",
    },
    "cpv": {
        "cabo verde",
        "cape verde",
        "tubarões azuis",
        "tubaraes azuis",
        "blue sharks",
        "crioulos",
    },
    "ksa": {"saudi arabia", "saudi", "green falcons"},
    "uru": {
        "uruguay",
        "uruguayan",
        "la celeste",
        "la garra charrúa",
        "la garra charrua",
        "selección uruguaya",
        "seleccion uruguaya",
        "selección de uruguay",
        "seleccion de uruguay",
    },
    # Group I
    "fra": {
        "france",
        "french",
        "les bleus",
        "les tricolores",
        "équipe de france",
        "equipe de france",
    },
    "sen": {
        "senegal",
        "senegalese",
        "lions of teranga",
        "teranga lions",
        "équipe du sénégal",
        "equipe du senegal",
    },
    "irq": {"iraq", "iraqi", "lions of mesopotamia", "usood al-rafidain"},
    "nor": {"norway", "norwegian", "landslaget"},
    # Group J
    "arg": {
        "argentina",
        "argentinian",
        "la albiceleste",
        "albiceleste",
        "los campeones del mundo",
        "selección argentina",
        "seleccion argentina",
        "selección de argentina",
        "seleccion de argentina",
    },
    "alg": {
        "algeria",
        "algerian",
        "les fennecs",
        "fennec foxes",
        "desert foxes",
        "équipe d'algérie",
        "equipe d'algerie",
    },
    "aut": {"austria", "austrian", "das team"},
    "jor": {"jordan", "jordanian", "al-nashama", "nashama"},
    # Group K
    "por": {
        "portugal",
        "portuguese",
        "a seleção",
        "a selecao",
        "a seleção das quinas",
        "navegadores",
        "seleção portuguesa",
        "selecao portuguesa",
    },
    "cod": {
        "congo dr",
        "dr congo",
        "democratic republic of congo",
        "les léopards",
        "les leopards",
        "leopards",
        "drc",
    },
    "uzb": {"uzbekistan", "uzbek", "white wolves"},
    "col": {
        "colombia",
        "colombian",
        "los cafeteros",
        "cafeteros",
        "selección colombiana",
        "seleccion colombiana",
        "selección de colombia",
        "seleccion de colombia",
    },
    # Group L
    "eng": {"england", "english", "three lions"},
    "cro": {"croatia", "croatian", "vatreni", "kockasti", "the chequered ones", "hrvatska"},
    "gha": {"ghana", "ghanaian", "black stars"},
    "pan": {
        "panama",
        "panamanian",
        "los canaleros",
        "canaleros",
        "selección panameña",
        "seleccion panamena",
        "selección de panamá",
        "seleccion de panama",
    },
}

# ── Retired players ───────────────────────────────────────────────────────────
# Players who retired before 2025 — should never appear in 2026 squad news.

RETIRED_PLAYERS = {
    # Czech Republic
    "petr čech",
    "tomas rosicky",
    "tomáš rosický",
    "milan baros",
    "milan baroš",
    "pavel nedved",
    "pavel nedvěd",
    # Bosnia
    "miralem pjanic",
    "miralem pjanić",
    "asmir begovic",
    "asmir begović",
    # Canada
    "atiba hutchinson",
    "julian de guzman",
    "julian de guzmán",
    "dwayne de rosario",
    # Other commonly hallucinated retired players
    "xavi",
    "xavi hernandez",
    "xavi hernández",
    "iniesta",
    "andres iniesta",
    "andrés iniesta",
    "david villa",
    "carles puyol",
    "miroslav klose",
    "bastian schweinsteiger",
    "philipp lahm",
    "frank lampard",
    "steven gerrard",
    "john terry",
    "zlatan ibrahimovic",
    "zlatan ibrahimović",
    "didier drogba",
    "samuel eto'o",
    "ryan giggs",
    "paul scholes",
    "gianluigi buffon",
    "andrea pirlo",
    "daniele de rossi",
    "sergio ramos",
    "marcelo",
    "david luiz",
    "dani alves",
    "thomas muller",
    "thomas müller",
    "manuel neuer",
    "toni kroos",
    "mats hummels",
    "claudio bravo",
    "arturo vidal",
    "tim cahill",
    "mark schwarzer",
    "gerard pique",
    "gerard piqué",
    "david silva",
    "cesc fabregas",
    "cesc fàbregas",
    "walid regragui",
    "andres guardado",
    "andrés guardado",
    "javier hernandez",
    "javier hernández",
    "michael owen",
    "diego godin",
    "diego godín",
    "yaya toure",
    "yaya touré",
    "ronaldinho",
    "kaka",
    "kaká",
}

# ── Boilerplate headline phrases ──────────────────────────────────────────────
# Generic phrases that indicate a hallucinated or non-specific headline.

BOILERPLATE_PHRASES = {
    "squad selection process underway",
    "squad selection process begins",
    "training camp dates announced",
    "training camp dates set",
    "friendly matches confirmed",
    "friendly matches scheduled",
    "friendly matches announced",
    "tactical preparations underway",
    "tactical preparations begin",
    "squad injury updates",
    "preparation plans revealed",
    "world cup preparation plans",
    "squad morale high",
    "fan engagement",
    "media coverage",
}

# ── Team context ──────────────────────────────────────────────────────────────
# Verified coach name and best sources per team — prevents coach hallucination.

TEAM_CONTEXT: dict[str, dict] = {
    "mex": {
        "coach": "Javier Aguirre",
        "sources": "Medio Tiempo, Record (Mexico), ESPN Deportes, The Washington Post",
    },
    "rsa": {
        "coach": "Hugo Broos",
        "sources": "KickOff, SuperSport Africa, CAF Online, FourFourTwo",
    },
    "kor": {
        "coach": "Hong Myung-bo",
        "sources": "FIFA.com, FourFourTwo, Fox Sports Asia, Goal.com Asia",
    },
    "cze": {"coach": "Miroslav Koubek", "sources": "FIFA.com, UEFA.com, FourFourTwo"},
    "can": {"coach": "Jesse Marsch", "sources": "Sportsnet, TSN, The Canadian Press, FIFA.com"},
    "bih": {
        "coach": "Sergej Barbarez",
        "sources": "UEFA.com, FIFA.com, FourFourTwo, Footy Headlines",
    },
    "qat": {
        "coach": "Julen Lopetegui",
        "sources": "FIFA.com, Gulf News Sport, Saudi Gazette Sport",
    },
    "sui": {
        "coach": "Murat Yakin",
        "sources": "Swiss Football Association, blue News, Blick, FIFA.com",
    },
    "bra": {
        "coach": "Carlo Ancelotti",
        "sources": "Globo Esporte, Lance!, Inside World Football, CNN Brasil, FourFourTwo",
    },
    "mar": {"coach": "Mohamed Ouahbi", "sources": "CAF Online, FIFA.com, Goal.com, FourFourTwo"},
    "hai": {"coach": "Sébastien Migné", "sources": "FIFA.com, FourFourTwo, Concacaf.com"},
    "sco": {"coach": "Steve Clarke", "sources": "BBC Sport, Sky Sports, The Guardian, FIFA.com"},
    "usa": {"coach": "Mauricio Pochettino", "sources": "ESPN, AS.com, The Athletic, The Guardian"},
    "par": {
        "coach": "Gustavo Alfaro",
        "sources": "ESPN Deportes, TyC Sports, CONMEBOL.com, FourFourTwo",
    },
    "aus": {
        "coach": "Tony Popovic",
        "sources": "Fox Sports Australia, The Roar, 7NEWS Australia, FourFourTwo",
    },
    "tur": {"coach": "Vincenzo Montella", "sources": "FIFA.com, FourFourTwo, Al Jazeera"},
    "ger": {
        "coach": "Julian Nagelsmann",
        "sources": "Bundesliga, beIN SPORTS, FIFA.com, FourFourTwo",
    },
    "cur": {"coach": "Fred Rutten", "sources": "FIFA.com, FourFourTwo, beIN SPORTS"},
    "civ": {"coach": "Emerse Faé", "sources": "CAF Online, FIFA.com, FourFourTwo"},
    "ecu": {
        "coach": "Sebastián Beccacece",
        "sources": "ESPN Deportes, CONMEBOL.com, The Guardian, FourFourTwo",
    },
    "ned": {
        "coach": "Ronald Koeman",
        "sources": "UEFA.com, Voetbal International, The Athletic, FourFourTwo",
    },
    "jpn": {"coach": "Hajime Moriyasu", "sources": "FIFA.com, FourFourTwo, Nikkan Sports, ESPN"},
    "swe": {
        "coach": "Graham Potter",
        "sources": "UEFA.com, The Guardian, Sky Sports, FourFourTwo, The Washington Post",
    },
    "tun": {
        "coach": "Sabri Lamouchi",
        "sources": "CAF Online, La Presse de Tunisie, Futaa.com, FourFourTwo",
    },
    "bel": {"coach": "Rudi Garcia", "sources": "FIFA.com, The Brussels Times, FourFourTwo"},
    "egy": {"coach": "Hossam Hassan", "sources": "Egypt Today, FIFA.com, CAF Online, FourFourTwo"},
    "irn": {
        "coach": "Amir Ghalenoei",
        "sources": "FourFourTwo, Associated Press, The Washington Post, Al Jazeera",
    },
    "nzl": {"coach": "Darren Bazeley", "sources": "FIFA.com, FourFourTwo, The Roar"},
    "esp": {"coach": "Luis de la Fuente", "sources": "Marca, AS.com, FIFA.com, FourFourTwo"},
    "cpv": {"coach": "Bubista", "sources": "FIFA.com, CAF Online, FourFourTwo"},
    "ksa": {"coach": "Hervé Renard", "sources": "Arab News, Saudi Pro League, FourFourTwo"},
    "uru": {"coach": "Marcelo Bielsa", "sources": "ESPN, AS.com, FourFourTwo, TyC Sports"},
    "fra": {"coach": "Didier Deschamps", "sources": "Le Monde, L'Equipe, FIFA.com"},
    "sen": {"coach": "Pape Thiaw", "sources": "CAF Online, FIFA.com, FourFourTwo"},
    "irq": {"coach": "Graham Arnold", "sources": "The Guardian, FIFA.com, FourFourTwo, Le Monde"},
    "nor": {"coach": "Ståle Solbakken", "sources": "FIFA.com, FourFourTwo, Goal.com, Le Monde"},
    "arg": {
        "coach": "Lionel Scaloni",
        "sources": "TyC Sports, Ole.com.ar, ESPN Deportes, FourFourTwo",
    },
    "alg": {
        "coach": "Vladimir Petković",
        "sources": "Algérie Presse Service, Pan Africa Football, CAF Online",
    },
    "aut": {"coach": "Ralf Rangnick", "sources": "FIFA.com, FourFourTwo, UEFA.com"},
    "jor": {"coach": "Jamal Sellami", "sources": "Jordan Times, Jordan Pulse, FIFA.com"},
    "por": {"coach": "Roberto Martínez", "sources": "A Bola, Record, El País, FourFourTwo"},
    "cod": {
        "coach": "Sébastien Desabre",
        "sources": "CAF Online, Sky Sports, FourFourTwo, FIFA.com",
    },
    "uzb": {"coach": "Fabio Cannavaro", "sources": "UzDaily.uz, FIFA.com, FourFourTwo"},
    "col": {
        "coach": "Néstor Lorenzo",
        "sources": "El País, ESPN Deportes, CONMEBOL.com, FourFourTwo",
    },
    "eng": {
        "coach": "Thomas Tuchel",
        "sources": "BBC Sport, The Guardian, Sky Sports, FourFourTwo",
    },
    "cro": {"coach": "Zlatko Dalić", "sources": "HRT, Croatia Week, FIFA.com, FourFourTwo"},
    "gha": {"coach": "Carlos Queiroz", "sources": "News Ghana, CAF Online, FourFourTwo, FIFA.com"},
    "pan": {
        "coach": "Thomas Christiansen",
        "sources": "FIFA.com, FourFourTwo, Concacaf.com, AS.com",
    },
}
