// Pure bracket-logic utilities — no React, fully testable in isolation.

// Builds the full 5-round bracket structure from a list of R32 fixtures and the user's picks.
// Each round's team slots are filled by the winner (real or picked) from the previous round.
export function buildBracketRounds(roundOf32, picks) {
    const r32 = applyPicks(roundOf32, picks);
    const roundOf16 = pairWinners("R16", r32, 8, picks, [
        "Philadelphia Stadium",
        "New York New Jersey Stadium",
        "Dallas Stadium",
        "Atlanta Stadium",
        "Seattle Stadium",
        "Vancouver Stadium",
        "Miami Stadium",
        "Kansas City Stadium",
    ]);
    const quarterfinals = pairWinners("QF", roundOf16, 4, picks, [
        "Boston Stadium",
        "Los Angeles Stadium",
        "Miami Stadium",
        "Kansas City Stadium",
    ]);
    const semifinals = pairWinners("SF", quarterfinals, 2, picks, [
        "Dallas Stadium",
        "Atlanta Stadium",
    ]);

    return [
        { name: "Round of 32", fixtures: r32 },
        { name: "Round of 16", fixtures: roundOf16 },
        { name: "Quarterfinals", fixtures: quarterfinals },
        { name: "Semifinals", fixtures: semifinals },
        {
            name: "Final",
            fixtures: applyPicks(
                [
                    {
                        displayId: "Final",
                        venue: "New York New Jersey Stadium",
                        sourceIds: ["SF-1", "SF-2"],
                        home: winnerOrPlaceholder(semifinals[0]),
                        away: winnerOrPlaceholder(semifinals[1]),
                    },
                ],
                picks
            ),
        },
    ];
}

// Creates the next round's fixtures by pairing consecutive winners from the previous round.
// Fixtures 0+1 feed match 1, fixtures 2+3 feed match 2, and so on.
// sourceIds links each new fixture back to its two feeder fixtures for connector line drawing.
export function pairWinners(prefix, previousFixtures, count, picks, venues) {
    return applyPicks(
        Array.from({ length: count }, (_, index) => {
            const first = previousFixtures[index * 2];
            const second = previousFixtures[index * 2 + 1];
            return {
                displayId: `${prefix}-${index + 1}`,
                venue: venues[index],
                sourceIds: [first?.displayId, second?.displayId].filter(Boolean),
                home: winnerOrPlaceholder(first),
                away: winnerOrPlaceholder(second),
            };
        }),
        picks
    );
}

// Merges user picks into fixtures, but only if the picked team is actually
// playing in that fixture. Prevents stale picks from a previous bracket state
// from showing up after the bracket is recalculated.
export function applyPicks(fixtures, picks) {
    return fixtures.map((fixture) => {
        const winner = canPickTeam(fixture, picks[fixture.displayId])
            ? picks[fixture.displayId]
            : fixture.winner;
        return { ...fixture, winner };
    });
}

// Returns the winner's name if the fixture is decided, otherwise a placeholder
// string like "Winner R32-3" that the next round can display until the pick is made.
export function winnerOrPlaceholder(fixture) {
    return fixture?.winner ?? `Winner ${fixture?.displayId ?? "TBD"}`;
}

// Returns true only if the team name matches one of the two actual teams in the fixture.
// Guards against picking a placeholder string like "Winner R32-3" as a winner.
export function canPickTeam(fixture, teamName) {
    return teamName === fixture.home || teamName === fixture.away;
}

// Returns true if the name is a real team rather than a placeholder.
// Placeholder strings start with "Winner " (generated by winnerOrPlaceholder)
// or "Pending" (set by the backend for unscheduled slots).
export function isConcreteTeam(name) {
    return Boolean(name) && !name.startsWith("Winner ") && !name.startsWith("Pending");
}

// A fixture is locked when real match data is active and the match has been played.
// Locked fixtures can't be manually picked or reordered.
export function isLockedFixture(fixture, mode) {
    return mode === "real" && fixture.locked === true;
}

// Parses the drag payload set in TeamPickRow. Returns null if the data is missing
// or malformed so the drop handler can safely bail out.
export function readDragPayload(event) {
    try {
        const raw = event.dataTransfer.getData("application/json");
        return raw ? JSON.parse(raw) : null;
    } catch {
        return null;
    }
}

// Finds all fixture IDs that depend on a given fixture, across all future rounds.
// Used when a pick changes — any fixture that could be affected needs its pick cleared.
// Works like a breadth-first search: start from the changed fixture, then find everything
// downstream by following sourceIds round by round.
export function descendantFixtureIds(rounds, fixtureId) {
    const descendants = new Set();
    let frontier = new Set([fixtureId]);

    rounds.forEach((round) => {
        const nextFrontier = new Set();
        round.fixtures.forEach((fixture) => {
            if (fixture.sourceIds?.some((sourceId) => frontier.has(sourceId))) {
                descendants.add(fixture.displayId);
                nextFrontier.add(fixture.displayId);
            }
        });
        if (nextFrontier.size) frontier = nextFrontier;
    });

    return descendants;
}

// Generates an SVG path string for a rounded connector line between two fixtures.
// The line travels horizontally from the source, bends at the midpoint, then
// continues horizontally to the target — like a bracket arm.
// Radius is capped so corners stay smooth even when fixtures are very close together.
export function connectorPath(x1, y1, x2, y2) {
    const gap = Math.max(24, x2 - x1);
    const midX = x1 + gap / 2;
    const direction = y2 >= y1 ? 1 : -1;
    const radius = Math.min(18, Math.abs(y2 - y1) / 2, gap / 4);

    // If the two fixtures are at the same vertical position, just draw a straight line.
    if (Math.abs(y2 - y1) < 1) {
        return `M ${x1} ${y1} H ${x2}`;
    }

    // SVG path commands:
    // M = move to start, H = horizontal line, Q = quadratic bezier curve (the rounded corner), V = vertical line
    return [
        `M ${x1} ${y1}`,
        `H ${midX - radius}`,
        `Q ${midX} ${y1} ${midX} ${y1 + direction * radius}`,
        `V ${y2 - direction * radius}`,
        `Q ${midX} ${y2} ${midX + radius} ${y2}`,
        `H ${x2}`,
    ].join(" ");
}
